/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektzp.src.panel;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;


/**
 *
 * @author Grzegorz
 */
public class panel extends javax.swing.JPanel {

    /**
     * Creates new form panel
     */
    private boolean Tryb_ciemny = false;
    private int Figura=0;
    private int pokazfigure=0;
    String labelgraniastoslup[] = { "Prostokąt", "Pięciobok", "Trójkąt"};
    final DefaultComboBoxModel modelgraniastoslup = new DefaultComboBoxModel(labelgraniastoslup);
    String labelostroslup[] = {"Prostokąt", "Pięciobok", "Trójkąt"};
    final DefaultComboBoxModel modelostroslup = new DefaultComboBoxModel(labelostroslup);
    String labelstozek[] = {"Okrąg"};
    final DefaultComboBoxModel modelstozek = new DefaultComboBoxModel(labelstozek);
    String labelwalec[] = {"Okrąg"};
    final DefaultComboBoxModel modelwalec = new DefaultComboBoxModel(labelwalec);
    public panel() {
        initComponents();
        this.setBackground(Color.WHITE); 
        odswiezdane();
        ///ukrycie figur
        jLabel7.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jButton1.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenuBar9 = new javax.swing.JMenuBar();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("jMenu9");

        jMenu10.setText("File");
        jMenuBar5.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar5.add(jMenu11);

        jMenu12.setText("File");
        jMenuBar6.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar6.add(jMenu13);

        jMenu14.setText("File");
        jMenuBar7.add(jMenu14);

        jMenu15.setText("Edit");
        jMenuBar7.add(jMenu15);

        jMenu16.setText("File");
        jMenuBar8.add(jMenu16);

        jMenu17.setText("Edit");
        jMenuBar8.add(jMenu17);

        jMenu18.setText("File");
        jMenuBar9.add(jMenu18);

        jMenu19.setText("Edit");
        jMenuBar9.add(jMenu19);

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setMaximumSize(new java.awt.Dimension(400, 40));
        setPreferredSize(new java.awt.Dimension(500, 500));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graniastosłup", "Ostrosłup", "Stożek", "Walec", "Kula" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prostokąt", "Pięciobok", "Trójkąt", "Okrąg" }));
        jComboBox2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jComboBox2ComponentHidden(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Oblicz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Typ figury przestrzennej");

        jLabel2.setText("Podstawa bryły");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/ss3.png"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel7.setMaximumSize(new java.awt.Dimension(214, 206));
        jLabel7.setMinimumSize(new java.awt.Dimension(214, 206));

        jCheckBox1.setText("Pokaż Figurę");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel12.setText("Bok A/promień podstawy:");

        jLabel13.setText("Bok B podstawy:");

        jLabel15.setText("Wysokość figury przestrzennej:");

        jLabel14.setText("Wysokość podstawy:");

        jLabel16.setText("Wynik:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14))
                                        .addGap(29, 29, 29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(67, 67, 67)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jCheckBox1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(813, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))))))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
        //pokazywanie figur po kolei z comboboxem
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            pokazaniefigury();
        } catch (IOException ex) {
        }
        odswiezdane();
        pokazfieldlabel();
//GEN-LAST:event_jComboBox1ActionPerformed
            // ukrycie comboboxa 2 w momencie gdy ustawi się combobox1 na 4
        if(jComboBox1.getSelectedIndex() == 0){
            jComboBox2.setVisible(true);
            jLabel2.setVisible(true);
         }else if (jComboBox1.getSelectedIndex() == 1){
            jComboBox2.setVisible(true);
            jLabel2.setVisible(true);
         }else if (jComboBox1.getSelectedIndex() == 2){
            jComboBox2.setVisible(true);
            jLabel2.setVisible(true);
         }else if (jComboBox1.getSelectedIndex() == 3){
            jComboBox2.setVisible(true);
            jLabel2.setVisible(true);
         }else if (jComboBox1.getSelectedIndex() == 4){
            jComboBox2.setVisible(false);
            jLabel2.setVisible(false);
         }
        // ukrycie textfieldów w zależności od ustawionej figury
          
       }

    

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
       
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
         jTextField1.setEnabled(true);
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //graniastoslup-prostokat
        if(jComboBox1.getSelectedIndex()==0 && jComboBox2.getSelectedIndex()==0){
            int A = Integer.parseInt(jTextField1.getText());
            int B = Integer.parseInt(jTextField2.getText());
            int h = Integer.parseInt(jTextField4.getText());
            double W = A*B*h;
            jTextField5.setText(String.valueOf(W));
           
            
        //graniastoslup-pieciobok    
        }else if(jComboBox1.getSelectedIndex()==0 && jComboBox2.getSelectedIndex()==1){
            int A = Integer.parseInt(jTextField1.getText());
            int h = Integer.parseInt(jTextField4.getText());
            double W = 1.72048*(A*A)*h;
            jTextField5.setText(String.valueOf(W));
        //graniastoslup-trojkat
        }else if(jComboBox1.getSelectedIndex()==0 && jComboBox2.getSelectedIndex()==2){
            int A = Integer.parseInt(jTextField1.getText());
            int H = Integer.parseInt(jTextField3.getText());
            int h = Integer.parseInt(jTextField4.getText());
            double W = A*H*h;
            jTextField5.setText(String.valueOf(W));
        //ostroslup-prostokat     
        }else if(jComboBox1.getSelectedIndex()==1 && jComboBox2.getSelectedIndex()==0){
            int A = Integer.parseInt(jTextField1.getText());
            int B = Integer.parseInt(jTextField2.getText());
            int h = Integer.parseInt(jTextField4.getText());
            double W = ((A*B)/3)*h;
            jTextField5.setText(String.valueOf(W));
        //ostroslup-pięciąkąt  
        }else if(jComboBox1.getSelectedIndex()==1 && jComboBox2.getSelectedIndex()==1){
            int A = Integer.parseInt(jTextField1.getText());
            int H = Integer.parseInt(jTextField3.getText());
            double W = ((A*A)/3)*H;
            jTextField5.setText(String.valueOf(W));
            //ostrosłup trójkąt
        }else if(jComboBox1.getSelectedIndex()==1 && jComboBox2.getSelectedIndex()==2){
            int A = Integer.parseInt(jTextField1.getText());
            int H = Integer.parseInt(jTextField3.getText());
            int h = Integer.parseInt(jTextField4.getText());
            double W = ((A*H)/3*h);
            jTextField5.setText(String.valueOf(W));
        //stozek    
        }else if(jComboBox1.getSelectedIndex()==2){
            int B = Integer.parseInt(jTextField2.getText());
            int h = Integer.parseInt(jTextField3.getText());
            double W = ((Math.pow(B, 2)*3.14)*h/3);
            jTextField5.setText(String.valueOf(W));
        //walec    
        }else if(jComboBox1.getSelectedIndex()==3){
            int B = Integer.parseInt(jTextField2.getText());
            int h = Integer.parseInt(jTextField3.getText());
            double W=(Math.pow(B, 2)*3.14)*h;
            jTextField5.setText(String.valueOf(W));
        //kula    
        }else if(jComboBox1.getSelectedIndex()==4 ){
            int A = Integer.parseInt(jTextField2.getText());
            double W=((Math.pow(A, 3)*3.14)*4)/3;
            jTextField5.setText(String.valueOf(W));
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1FocusGained

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            pokazaniefigury();
        } catch (IOException ex) {
        }
        pokazfieldlabel();
    }
    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        jTextField3.setText("");
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        jTextField4.setText("");
    }//GEN-LAST:event_jTextField4FocusGained

    private void jComboBox2ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBox2ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ComponentHidden

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()){
            try {
                pokazaniefigury();
            } catch (IOException ex) {
            }
        }else{
        jLabel7.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    public int getpokazfigure(){
    return pokazfigure;
}
    public int getFigura(){
    return Figura;
}
    public void odswiezdane(){
        if (jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 0){
            jComboBox2.setModel(modelgraniastoslup);
        }else if (jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 1){
            jComboBox2.setModel(modelgraniastoslup);
        }else if (jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 2){
            jComboBox2.setModel(modelgraniastoslup);
        }else if (jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 0){
            jComboBox2.setModel(modelostroslup);
        }else if (jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 1){
            jComboBox2.setModel(modelostroslup);
        }else if (jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 2){
            jComboBox2.setModel(modelostroslup);
        }else if (jComboBox1.getSelectedIndex() == 2){
            jComboBox2.setModel(modelstozek);
        }else if (jComboBox1.getSelectedIndex() == 3){
            jComboBox2.setModel(modelwalec);
        }
    }
public void pokazaniefigury() throws IOException{
    if(jCheckBox1.isSelected()){ 
        jLabel7.setVisible(true);
        if(jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 0){
          jLabel7.validate();
          jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/ss3.png")));
         }else if (jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 1){
            jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/ss4.png")));
            jLabel7.revalidate();
         }else if (jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 2){
          jLabel7.setIcon(new ImageIcon(ImageIO.read(new File("/panel/ss5.png"))));
         }else if (jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 0){
           jLabel7.setIcon(new ImageIcon(ImageIO.read(new File("/panel/ss2.png"))));
          }else if (jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 1){
         jLabel7.setIcon(new ImageIcon(ImageIO.read(new File("/panel/ss8.png"))));
           }else if (jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 2){
          jLabel7.setIcon(new ImageIcon(ImageIO.read(new File("/panel/ss4.png"))));
           }else if (jComboBox1.getSelectedIndex() == 2){
          jLabel7.setIcon(new ImageIcon(ImageIO.read(new File("/panel/ss6.png"))));
           }else if (jComboBox1.getSelectedIndex() == 3){
          jLabel7.setIcon(new ImageIcon(ImageIO.read(new File("/panel/ss7.png"))));
           }else if (jComboBox1.getSelectedIndex() == 4){
         jLabel7.setIcon(new ImageIcon(ImageIO.read(new File("/panel/ss9.jpg"))));
           }
    }
    
}
public void pokazfieldlabel(){
    if(jComboBox1.getSelectedIndex() ==0 && jComboBox2.getSelectedIndex() ==0){          //graniastosłup prostokąt       
        jTextField1.setEnabled(true);
        jTextField1.setVisible(true);
        jTextField2.setEnabled(true);
        jTextField2.setVisible(true);
        jTextField3.setEnabled(false);
        jTextField3.setVisible(false);
        jTextField4.setEnabled(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        jLabel14.setVisible(false);
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        jButton1.setVisible(true);
        }else if(jComboBox1.getSelectedIndex()==0 && jComboBox2.getSelectedIndex() == 1){           //graniastosłup pięciokąt       
        jTextField1.setEnabled(true);
        jTextField1.setVisible(true);
        jTextField2.setEnabled(false);
        jTextField2.setVisible(false);
        jTextField3.setEnabled(false);
        jTextField3.setVisible(false);
        jTextField4.setEnabled(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        jButton1.setVisible(true);
        }else if(jComboBox1.getSelectedIndex()==0 && jComboBox2.getSelectedIndex() == 2){           //trojkat      
        jTextField1.setEnabled(true);
        jTextField1.setVisible(true);
        jTextField2.setEnabled(false);
        jTextField2.setVisible(false);
        jTextField3.setEnabled(true);
        jTextField3.setVisible(true);
        jTextField4.setEnabled(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(false);
        jLabel14.setVisible(true);
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        jButton1.setVisible(true);

    }else if(jComboBox1.getSelectedIndex()==1 && jComboBox2.getSelectedIndex()== 0){          //ostroslup prostokąt
        jTextField1.setEnabled(true);
        jTextField1.setVisible(true);
        jTextField2.setEnabled(true);
        jTextField2.setVisible(true);
        jTextField3.setEnabled(false);
        jTextField3.setVisible(false);
        jTextField4.setEnabled(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        jLabel14.setVisible(false);
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        jButton1.setVisible(true);
    }else if(jComboBox1.getSelectedIndex()==1 && jComboBox2.getSelectedIndex()==1){          //ostroslup pięciokąt
        jTextField1.setEnabled(true);
        jTextField1.setVisible(true);
        jTextField2.setEnabled(false);
        jTextField2.setVisible(false);
        jTextField3.setEnabled(true);
        jTextField3.setVisible(true);
        jTextField4.setEnabled(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(false);
        jLabel14.setVisible(true);
        jLabel15.setVisible(false);
        jLabel16.setVisible(true);
        jButton1.setVisible(true);
    }else if(jComboBox1.getSelectedIndex()==1 && jComboBox2.getSelectedIndex()==2){          //ostroslup trójkąt
        jTextField1.setEnabled(true);
        jTextField1.setVisible(true);
        jTextField2.setEnabled(false);
        jTextField2.setVisible(false);
        jTextField3.setEnabled(true);
        jTextField3.setVisible(true);
        jTextField4.setEnabled(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(false);
        jLabel14.setVisible(true);
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        jButton1.setVisible(true);
    }else if(jComboBox1.getSelectedIndex()==2){         //stozek
        jTextField1.setEnabled(false);
        jTextField1.setVisible(false);
        jTextField2.setEnabled(true);
        jTextField2.setVisible(true);
        jTextField3.setEnabled(true);
        jTextField3.setVisible(true);
        jTextField4.setEnabled(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(true);
        jLabel12.setVisible(false);
        jLabel13.setVisible(true);
        jLabel14.setVisible(true);
        jLabel15.setVisible(false);
        jLabel16.setVisible(true);
        jButton1.setVisible(true);
        }else if(jComboBox1.getSelectedIndex()==3){   //walec    
        jTextField1.setEnabled(false);
        jTextField1.setVisible(false);
        jTextField2.setEnabled(true);
        jTextField2.setVisible(true);
        jTextField3.setEnabled(true);
        jTextField3.setVisible(true);
        jTextField4.setEnabled(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(true);
        jLabel12.setVisible(false);
        jLabel13.setVisible(true);   
        jLabel14.setVisible(true);
        jLabel15.setVisible(false);
        jLabel16.setVisible(true);
        jButton1.setVisible(true);
    }else if(jComboBox1.getSelectedIndex()==4){         //kula
        jTextField1.setEnabled(false);
        jTextField1.setVisible(false);
        jTextField2.setEnabled(true);
        jTextField2.setVisible(true);
        jTextField3.setEnabled(false);
        jTextField3.setVisible(false);
        jTextField4.setEnabled(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(true);
        jLabel12.setVisible(false);
        jLabel13.setVisible(true);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(true);
        jButton1.setVisible(true);
    }
    
    
}
public void setFigura(int value){
    Figura=value;
}
 public void  setTryb_ciemny(boolean value){
        Tryb_ciemny = value;
        Tryb_ciemny();
    }  
    public boolean getTryb_ciemny(){
        return Tryb_ciemny;
    }
    public void Tryb_ciemny(){
        if (getTryb_ciemny() == false){
            this.setBackground(Color.WHITE);
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
            jLabel12.setForeground(Color.BLACK);
            jLabel13.setForeground(Color.BLACK);
            jLabel14.setForeground(Color.BLACK);
            jLabel15.setForeground(Color.BLACK);
            jLabel16.setForeground(Color.BLACK);
            jTextField1.setForeground(Color.BLACK);
            jTextField2.setForeground(Color.BLACK);
            jTextField3.setForeground(Color.BLACK);
            jTextField4.setForeground(Color.BLACK);
            jTextField5.setForeground(Color.BLACK);
            
            jTextField1.setBackground(Color.WHITE);
            jTextField2.setBackground(Color.WHITE);
            jTextField3.setBackground(Color.WHITE);
            jTextField4.setBackground(Color.WHITE);
            jTextField5.setBackground(Color.WHITE);
            
            
            jComboBox1.setForeground(Color.BLACK);
            jComboBox2.setForeground(Color.BLACK);
            
            jComboBox1.setBackground(Color.WHITE);
            jComboBox2.setBackground(Color.WHITE);
            
            jCheckBox1.setForeground(Color.BLACK);
            
            
            //jTextField9.setBackground(Color.WHITE);
        }else if (getTryb_ciemny() == true) {
            this.setBackground(Color.BLACK);
            jLabel1.setForeground(Color.WHITE);
            jLabel2.setForeground(Color.WHITE);
            jLabel12.setForeground(Color.WHITE);
            jLabel13.setForeground(Color.WHITE);
            jLabel14.setForeground(Color.WHITE);
            jLabel15.setForeground(Color.WHITE);
            jLabel16.setForeground(Color.WHITE);
            
            jTextField1.setForeground(Color.WHITE);
            jTextField2.setForeground(Color.WHITE);
            jTextField3.setForeground(Color.WHITE);
            jTextField4.setForeground(Color.WHITE);
            jTextField5.setForeground(Color.WHITE);
            
            jTextField1.setBackground(Color.BLACK);
            jTextField2.setBackground(Color.BLACK);
            jTextField3.setBackground(Color.BLACK);
            jTextField4.setBackground(Color.BLACK);
            jTextField5.setBackground(Color.BLACK);
            //jTextField9.setBackground(Color.BLACK);
            
            jComboBox1.setForeground(Color.WHITE);
            jComboBox2.setForeground(Color.WHITE);
            
            jComboBox1.setBackground(Color.BLACK);
            jComboBox2.setBackground(Color.BLACK);
            
            jCheckBox1.setForeground(Color.WHITE);
            
        }
        
    }
//to mialo byc do znikania jtextfield, ktore nie beda uzywane do aktualnego liczenia, ale poki co nie dziala
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JMenuBar jMenuBar9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }
}
